name: price_tracker
description: A price tracking app for Canadian stores.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  firebase_core: ^0.5.2
  url_launcher: ^5.7.10

  # Auth
  firebase_auth: ^0.18.1+2
  google_sign_in: ^4.5.5
  flutter_twitter_login: ^1.1.0
  flutter_signin_button: ^1.1.0

  # Analytics
  firebase_analytics: ^6.2.0
  firebase_crashlytics: ^0.2.3

  # Database and notifications
  cloud_firestore: ^0.14.3
  cloud_functions: ^0.7.0+1
  firebase_messaging: ^8.0.0-dev.8
  flutter_local_notifications: ^3.0.1+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
