name: price_tracker
description: A price tracking app for Canadian stores.
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+3
  firebase_core: ^0.5.3
  url_launcher: ^5.7.10

  # Auth
  firebase_auth: ^0.18.4+1
  google_sign_in: ^4.5.6
  flutter_twitter_login:
    git: git://github.com/eudangeld/flutter_twitter_login.git
  flutter_signin_button: ^1.1.0

  # Analytics
  firebase_analytics: ^6.3.0
  firebase_crashlytics: ^0.2.4

  # Database and notifications
  cloud_firestore: ^0.14.4
  cloud_functions: ^0.7.2
  firebase_messaging: ^8.0.0-dev.11
  flutter_local_notifications: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
