name: price_tracker
description: A price tracking app for Canadian stores.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  firebase_core: ^0.5.0+1

  # Auth
  firebase_auth: ^0.18.1+2
  google_sign_in: ^4.5.5
  # flutter_twitter_login: ^1.1.0
  github_sign_in: ^0.0.3
  sign_in_with_apple: ^2.5.4
  flutter_signin_button: ^1.1.0

  # Analytics
  firebase_analytics: ^6.0.2
  firebase_crashlytics: ^0.2.1+1
  firebase_performance: ^0.4.0+2

  # Database and notifications
  cloud_firestore: ^0.14.1+3
  cloud_functions: ^0.6.0+1
  firebase_messaging: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
